### ISSUE TITLE
Proper align and make animation as well

### ISSUE THREAD

**Issue by vbhushankumar** [vbhushankumar/Portfolio#3]
![Issue_2](https://github.com/vbhushankumar/Portfolio/assets/147478463/f09a9704-b7b1-42a2-8df8-652ae856f5f0)

It should be like this.
![Issue_Solution](https://github.com/vbhushankumar/Portfolio/assets/147478463/b0dc5116-35e2-402d-845f-16c550d07d27)

**Comment by GyanDangi** [comment]
Let me assign.

**Comment by Rokusuke69** [comment]
assign me this #4 issue.

**Comment by vbhushankumar** [comment]
Okay @Rokusuke69 let resolve my issue.

**Comment by vbhushankumar** [comment]
Thanks @Rokusuke69 for resolving my issue.
